version: '3.9'

services:
  # Serviço Principal da API
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080 # Porta da API (Host:Container)
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    environment:
      - MANAGER_URL=https://vizzusolu.duckdns.org/evolution
    expose:
      - 8080

  # Serviço de Banco de Dados (PostgreSQL) - Adicionado
  postgres:
    image: postgres:16
    container_name: evolution_postgres
    restart: always
    environment:
      POSTGRES_USER: user # Altere estes valores no seu .env se não quiser usar os padrões
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: evolution_db
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net

  # Serviço de Cache (Redis) - Adicionado E CORRIGIDO
  redis:
    image: redis:latest
    container_name: evolution_redis
    restart: always
    # CORREÇÃO CRÍTICA: Mapeamento de porta alterado para evitar conflito com o N8N.
    ports:
      - "6380:6379" # Host (6380) para Container (6379)
    networks:
      - evolution-net

volumes:
  evolution_instances:
  evolution_postgres_data: # Volume para persistência do DB
  
networks:
  evolution-net:
    name: evolution-net
    driver: bridge